### ISSUE TITLE
Fails to compiled on Julia 1.0 (different `struct _jl_task_t`)

### ISSUE THREAD

**Issue by hessammehr** [TuringLang/Libtask#1]
@yebai I've been trying to update LibtaskBuilder to link against Julia 1.0 without much luck. In Julia 1.0 `struct _jl_task_t` [definition](https://github.com/JuliaLang/julia/blob/b2babff79182d2ce93f1eb6d0826ec1257480d71/src/julia.h#L1581) no longer has a `consumers` field. Any plans/ideas?

**Comment by yebai** [comment]
I think you need to use the `task.c` from branch 

https://github.com/TuringLang/Turing.jl/pull/469

The version on the master branch is not updated yet.
